[package]
name = "mkwpp-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.3", features = ["runtime-tokio"] }
actix-web = "4.9.0"
serde = "1.0.217"
serde_json = "1.0.138"
