name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v4
    - name: Rust Version
      run: rustup --version
    - name: Clippy Version
      run: cargo clippy --version
    - name: cargo-fmt version
      run: cargo fmt --version
    - name: Clippy
      run: cargo clippy --verbose -- -D warnings
    - name: Clippy --features=import_data_new
      run: cargo clippy --features=import_data_new --verbose -- -D warnings
    - name: Clippy --features=import_data_old
      run: cargo clippy --features=import_data_old --verbose -- -D warnings
    - name: Format
      run: cargo fmt --check --verbose
